# Lab assignment: perceptron training

In this assignment we will learn how perceptrons work and are trained.

## Guidelines

Throughout this notebook you will find empty cells that you will need to fill with your own code. Follow the instructions in the notebook and pay special attention to the following symbols.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>You will need to solve a question by writing your own code or answer in the cell immediately below or in a different file, as instructed.</td></tr>
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>This is a hint or useful observation that can help you solve this assignment. You should pay attention to these hints to better understand the assignment.</td></tr>
 <tr><td width="80"><img src="img/pro.png" style="width:auto;height:auto"></td><td>This is an advanced and voluntary exercise that can help you gain a deeper knowledge into the topic. Good luck!</td></tr>
</table>


During the assignment you will make use of several Python packages that might not be installed in your machine. If that is the case, you can install new Python packages with

    conda install PACKAGENAME
    
if you are using Python Anaconda. Else you should use

    pip install PACKAGENAME

You will need the following packages for this particular assignment. Make sure they are available before proceeding:

* **numpy**
* **scikit-learn**

Lastly, if you need any help on the usage of a Python function you can place the writing cursor over its name and press Caps+Shift to produce a pop-out with related documentation. This will only work inside code cells.

Let's go!

## The AND and OR problems

Let us define the AND and OR problems in the **dataset** form we will be using throughout this assignment. A dataset is composed of two matrices X and Y, storing respectively the **inputs** fed to the networks and the desired **outputs** or **targets** for such inputs. We will use numpy's arrays for this purpose:

In [1]:
import numpy as np

X_and = np.array([[1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
Y_and = np.array([[0], [0], [0], [1]])
X_or = X_and.copy()  # same inputs as for AND
Y_or = np.array([[0], [1], [1], [1]])
print(X_and)
print(Y_and)
print(X_or)
print(Y_or)

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0]
 [0]
 [0]
 [1]]
[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0]
 [1]
 [1]
 [1]]


Note that in the patterns above we have prepended a 1, so that the **weights** **w** also include the **bias** term b and a dot product of the form **w**·**x** actually computes **w**·**x** + b. Hence, in this particular case **w** = (b, w1, w2).

## Perceptrons

As you have seen in the theory, **perceptrons** are based on the **McCulloch-Pitts neuron**, which is a simplified version of a neuron in the human brain. The **activation function** of this neuron is 1 when its inputs are greater than or equal to 0, and 0 otherwise:

In [2]:
def step_activation(x):
    return 1 * (x >= 0)  # multiply by 1 to change from boolean to int

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Figure out by yourself some values for <b>w</b> which solve the AND and OR problems. Store them in 2 variables called <b>w_and</b> and <b>w_or</b>.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
It may help if you print the points in (x1, x2) axes and interpret <b>w</b> and b as a hyperplane.
 </td></tr>
</table>

If your weights are correct, the following should output true:

In [3]:
####### INSERT YOUR CODE HERE

w_and = [-1.5, 1, 1]
w_or = [-0.5, 1, 1]

In [4]:
print(np.all(step_activation(X_and.dot(w_and)) == Y_and.ravel()))
print(np.all(step_activation(X_or.dot(w_or)) == Y_or.ravel()))

True
True


Observe that we are already taking advantage of **matrix calculus**: by multiplying above the input matrix with the weight vector we can simultaneously obtain the perceptron's outputs for all patterns. Then we just need to compare whether those outputs are actually the desired ones.

Let us code now **Rosenblatt's perceptron**, so that it learns automatically **w_and** and **w_or** for us, as they are both **linearly separable** problems.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Implement Rosenblatt's perceptron in a function called **perceptron_learn**. The inputs should be the X and Y matrices for the problem to be solved, and the output should be the **w** vector comprising both the bias and the actual weights.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Rosenblatt's algorithm operates in an **online** way, so you cannot take advantage of matrix calculus, as the weight vector **w** may change with every single pattern.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
For comparison purposes, initialize **w = 0**. The function **zeros** in numpy does exactly this.
 </td></tr>
</table>

In [5]:
def perceptron_learn(X, Y, max_iteration=100, learning_rate=1):
    w = np.zeros((X.shape[1], 1))
    np.random.seed(42)
    num_epochs = 0
    while True:
        for x, y in zip(X, Y):
            # compute perceptron output and error
            output = step_activation(x.dot(w))
            error = (y - output) * learning_rate
            if y != output:
                # update weights
                xtemp = np.reshape(x, (1, 3))
                w += error * xtemp.T
        num_epochs += 1

        if np.all(step_activation(X.dot(w).ravel()) == Y.ravel()) == True:
            print("Number of Epochs: ", num_epochs)
            break
        if num_epochs == max_iteration:
            print("Breaks without a valid answer")
            break
    return w.ravel()

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Test your implementation with the AND and OR problems. How many **epochs** are needed for convergence? What values do you get for **w_and** and **w_or**?
 </td></tr>
</table>

In [6]:
w_and = perceptron_learn(X_and, Y_and)
w_or = perceptron_learn(X_or, Y_or)

print("w_and =", w_and)
print("w_or =", w_or)

Number of Epochs:  5
Number of Epochs:  3
w_and = [-3.  2.  1.]
w_or = [-1.  1.  1.]


<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Verify that these new values for **w_and** and **w_or** do solve the respective problems. What happens if you initialize weights differently in **perceptron_learn**?
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Although Rosenblatt's algorithm states that all weights should be initialized to 0, you can initialize them randomly and convergence is still guaranteed.
 </td></tr>
</table>

In [7]:
####### INSERT YOUR CODE HERE
#we tried with random weights and got different values for w_and and w_or but all giving true as a result
print(np.all(step_activation(X_and.dot(w_and) == Y_and.ravel())))
print(np.all(step_activation(X_or.dot(w_or) == Y_or.ravel())))

True
True


Let us compare our implementation with that of *scikit-learn*. The class which implements a perceptron is **Perceptron**:

In [8]:
from sklearn.linear_model import Perceptron

Perceptron()

Perceptron()

In order to make things comparable, we need no regularization and not shuffling the patterns in each epoch:

In [9]:
Perceptron(alpha=0.0, shuffle=False)

Perceptron(alpha=0.0, shuffle=False)

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Train the scikit-learn perceptron for the AND and OR problems. Do you obtain the same values for **w_and** and **w_or**? Why/why not?
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Make sure that the parameter **n_iter** is at least as large as the number of epochs you obtained before.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Since *scikit-learn* splits weights (**coef_**) from biases (**intercept_**), we do not need to prepend anymore a 1 to the patterns. Be careful when feeding them to the **fit** method. Also, take this into account when checking the perceptron's output and comparing it to the one obtained with your method **perceptron_learn**.
 </td></tr>
</table>

In [10]:
####### INSERT YOUR CODE HERE
def cut_bias_multiplier(X):
    return np.delete(X, np.s_[0], axis=1)


def perceptron_scikit_learn(X, Y):
    # Train the perceptron for the AND problem
    X_train = cut_bias_multiplier(X)
    p = Perceptron(eta0=1, random_state=42)
    p.fit(X_train, Y.ravel())
    print(p.n_iter_)
    return np.concatenate((p.intercept_, p.coef_.ravel()))


w_and = perceptron_scikit_learn(X_and, Y_and)
print("w_and =", w_and)
w_or = perceptron_scikit_learn(X_or, Y_or)
print("w_or =", w_or)
# The values are differents because it has learnt from a different starting weight, Sklear percetron shuffle the dataset in each epoch

9
w_and = [-3.  2.  2.]
8
w_or = [-1.  2.  2.]


## The XOR problem

As you know from the theory, Rosenblatt's perceptrons can only solve **linearly separable** problems. The AND and OR problems fall into this category, but the XOR problem does not.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Define the XOR problem in two matrices **X_xor**, **Y_xor** as we did above for the AND and OR problems.
 </td></tr>
</table>

In [11]:
####### INSERT YOUR CODE HERE
X_xor = np.array([[1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
Y_xor = np.array([[0], [1], [1], [0]])

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Verify that **perceptron_learn** does not converge when given the XOR problem.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Introduce some control to exit the function after a maximum number of epochs has been reached. Otherwise, execution will go on forever and can stall your PC.
 </td></tr>
</table>

In [12]:
w_xor = perceptron_learn(X_xor, Y_xor)
print(np.all(step_activation(X_xor.dot(w_xor)) == Y_xor.ravel()))
print(w_xor)

Breaks without a valid answer
False
[ 0. -1.  0.]


<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Verify that scikit-learn's **Perceptron** does not converge either for the XOR problem.
 </td></tr>
</table>

In [13]:
####### INSERT YOUR CODE HERE
w_xor = perceptron_scikit_learn(X_xor, Y_xor)
print(np.all(step_activation(X_xor.dot(w_xor)) == Y_xor.ravel()))

6
False


## Multilayer perceptrons

Because of the limitations perceptrons have, **multilayer perceptrons (MLPs)** are usually the choice when dealing with general problems. Let us use for now the following class for an MLP:

In [14]:
class MLP(object):
    def __init__(self, sizes):
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]]
        self.weights = [
            np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])
        ]

So that an MLP is initialized with a list specifying the sizes of the different layers. For instance:

In [15]:
sizes = [2, 3, 1]
net = MLP(sizes)

Creates an MLP with 2 input neurons, 3 hidden neurons and 1 output neuron. <u>Note also the convention of the weights: they are created in such a way that *weights[i][j][k]* denotes the weight connecting neuron k of the i-th layer to neuron j of the (i+1)-th layer</u> (assuming that input layer is layer 0, first hidden layer is layer 1, and so on). <u>The same logic applies for biases, so that *biases[i][j]* is the bias of neuron j of the (i+1)-th layer</u>.

In [16]:
print("Number of layers: " + str(net.num_layers))
print("Sizes of layers: " + str(net.sizes))
print("Biases of hidden layer: " + str(net.biases[0]))
print("Biases of output layer: " + str(net.biases[1]))
print("Weights between input and hidden layer: " + str(net.weights[0]))
print("Weights between hidden and output layer: " + str(net.weights[1]))

Number of layers: 3
Sizes of layers: [2, 3, 1]
Biases of hidden layer: [[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]]
Biases of output layer: [[1.52302986]]
Weights between input and hidden layer: [[-0.23415337 -0.23413696]
 [ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]]
Weights between hidden and output layer: [[-0.46341769 -0.46572975  0.24196227]]


Let us assume for simplicity that all **activation functions** in our MLPs are going to be the *step_activation* defined above. Note that its implementation is vectorized, so that it works both for scalars and numpy arrays.

We can now easily program the **forward phase** of the **back-propagation** algorithm, that is, to input a pattern to the network and compute the network's outputs.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Implement the function **forward_phase(mlp, x)** that, given an MLP and an input vector **x**, computes the MLP's outputs when **x** is fed.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Take advantage of matrix calculus. Make sure to reshape the input vector to column form, so that the matrix-vector products do not raise errors.
 </td></tr>
</table>

In [159]:
####### INSERT YOUR CODE HERE
def forward_phase(mlp: MLP, X: np.ndarray, verbose=False):
    if len(X.shape) != 2 and x.shape[1] != 2:
        raise ValueError('X must be an array of (n,2) dimensions')
    outputs = []
    for x in X:
        next_phase_inputs_temp = x
        for i in range(mlp.num_layers - 1):
            weights = mlp.weights[i]
            bias = mlp.biases[i]
            number_of_conexions = len(weights)
            next_phase_inputs = np.zeros(number_of_conexions)
            for k in range(number_of_conexions):

                if verbose and k == 0:
                    print('layer_size', mlp.sizes[i])
                    print('next_layer_size', mlp.sizes[i + 1])
                    print("inputs", next_phase_inputs_temp)
                    print(f"weights_perceptron[{k}]", weights[k])
                    print(f"bias_perceptron[{k}]", bias[k])
                w = weights[k]
                product = next_phase_inputs_temp.dot(w.T)
                output = step_activation(product + bias[k])
                next_phase_inputs[k] = output
            if verbose:
                print("\nNew Inputs:", next_phase_inputs)
            next_phase_inputs_temp = next_phase_inputs
        outputs.append(next_phase_inputs[0])
    return np.array(outputs)

Since weights in the MLP class are initialized randomly, it is very unlikely that these initial weights actually solve the XOR problem.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Check whether the MLP created above does solve XOR or not.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Again, the MLP class splits weights from biases, so you should not feed to the networks the ones prepended to the patterns.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Because of matrix calculus, the return of **forward_phase** will be in matrix form, when it is actually a scalar since there is only a single output neuron. You may need to flatten return values to compare them to the actual outputs.
 </td></tr>
</table>

In [50]:
####### INSERT YOUR CODE HERE
X_xor_train = cut_bias_multiplier(X_xor)
X_xor_train_first = np.reshape(X_xor_train[0], (1, 2))
w_xor = forward_phase(net, X_xor_train_first)
print('only first w_xor', w_xor)
w_xor = forward_phase(net, X_xor_train)
print('whole dataset w_xor', w_xor)

[1. 1.]
[1.]
only first w_xor [1.]
[1. 1.]
[1.]
[1. 1.]
[1.]
[0. 1.]
[1.]
[1. 1.]
[1.]
whole dataset w_xor [1. 1. 1. 1.]


<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Build an MLP that actually solves XOR.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
You know from the theory that it suffices with a hidden layer of just 2 neurons. Because we have not coded any learning algorithm (we would need to program the whole back-propagation algorithm for that), you will have to set directly its weights and biases so that it does the job.
 </td></tr>
</table>

In [19]:
####### INSERT YOUR CODE HERE
sizes = [2, 2, 1]
net = MLP(sizes)

In [182]:
net.weights[0] = np.array([[-1, -1], [-1, -1]])
net.biases[0] = np.array([[.5], [1.5]])
net.biases[1] = np.array([[-.5]])
net.weights[1] = np.array([[-1, 1]])

In [184]:
X_xor_train

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [185]:
forward_phase(net, X_xor_train)

array([0., 1., 1., 0.])

Coding oneself the back-propagation algorithm is tedious and prone to errors (especially the **backward phase**), so it is only useful as an academic programming exercise. In practice, one resorts to implementations already available. *Scikit-learn* has two classes for MLPs, the **MLPClassifier** and the **MLPRegressor**:

In [23]:
from sklearn.neural_network import MLPClassifier, MLPRegressor

print(MLPClassifier())
print(MLPRegressor())

MLPClassifier()
MLPRegressor()


The only differences between the two are the **loss function** (**cross-entropy** for classification, **MSE** for regression) and the activation function of the output layer (**sigmoid** for classification, **identity** for regression). As you can see, the parameters used in construction are exactly the same ones, as well as the default values.

<table align="left">
 <tr><td width="80"><img src="img/question.png" style="width:auto;height:auto"></td><td>
Discuss which of the above parameters you can identify with those seen in the theory slides and which you cannot.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/pro.png" style="width:auto;height:auto"></td><td>
Take some classification dataset used in the SVM assignments and fit an *MLPClassifier* by modifying the parameters you deem appropriate. Report the best network configuration you can find. Can you beat the best SVM you obtained for that problem?
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/pro.png" style="width:auto;height:auto"></td><td>
Repeat with some regression dataset and an *MLPRegressor*. Are you able to beat the SVR?
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Beware of normalizing your data before feeding them to an MLP. It is advised to use a pipeline with a *StandardScaler*.
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="img/exclamation.png" style="width:auto;height:auto"></td><td>
Once in a pipeline, you can use grid search to try different choices for the MLP parameters.
 </td></tr>
</table>

<center>
~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.<br>
                          THIS IS THE END OF THE ASSIGNMENT<br>
~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.<br>
</center>